program demo_variables;
var
a,b: integer;

var
c: integer;
var demo1: integer;
var demo2: integer;
var demoEs3: integer;
var DemoEs4: integer;
var DEMOES5: integer;
var DeMo3Es6: integer;

var snake_case: string;
var _snake_case: string;
var __1_uno_: string;
var _1234_: string;

var func_tion: string;
integers, nombre: string;
reals:real;

var
is_18: boolean;
trauesa: boolean;

var btrues, atruesa: boolean;
sina: boolean;
formato: boolean;

var truesa, falsea: boolean;
var beging: boolean;

begin
	a:=47;
	b:= (a*a);
	c:= (b*b)*(a)+1;
    writeln("'a' value is:", a);
    writeln("'b' value is:", b);
    writeln("'c' value is:", c);
    writeln();
    writeln("'demo1' value is:", demo1);
    writeln("'demo2' value is:", demo2);
    writeln("'demoEs3' value is:", demoEs3);
    writeln("'DemoEs4' value is:", DemoEs4);
    writeln("'DEMOES5' value is:", DEMOES5);
    writeln("'DeMo3Es6' value is:", DeMo3Es6);
    writeln();

    snake_case := "soy snake_case";
    _snake_case := "soy _snake_case";
    __1_uno_ := "soy __1_uno_";

    writeln("'snake_case' value is:", snake_case);
    writeln("'_snake_case' value is:", _snake_case);
    writeln("'__1_uno_' value is:", __1_uno_);
    writeln("'_1234_' value is:", _1234_);
    //writeln("'function' value is:", function);
    writeln("'fun_ction' value is:", func_tion);
    writeln();
	writeln("integers: es", integers);
	writeln("reals: es", reals);
	writeln("nombre: es", nombre);
	writeln("is_18: es", is_18);
	writeln("atruesa: es", atruesa);
	writeln("btrues: es", btrues);
	writeln("formato: es", formato);
	writeln("sina: es", sina);
	writeln("truesa: es", truesa);
	writeln("falsea: es", falsea);
	writeln("beging: es", beging);
	writeln("False es", FALSE, "ó es", False);
	writeln("True es", TRUE, "ó es", True);

end.
